project:
  type: website

website:
  title: "quarto site customization"
  sidebar:
    contents:
      - href: index.qmd
        text: home
      - text: site navigation
        href: site-navigation.qmd

format:
  html:
    css: styles.css
    toc: true
    code-tools:
      source: true



